import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '../core/components/layout/Navbar';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} ${plusJakartaSans.className} relative h-max antialiased`} data-theme="fantasy">
        <div className="fixed left-0 top-0 z-10 min-h-screen w-full bg-gradient-to-br from-white/40 via-[#E9E9DE]/10 to-[#F6E4B6]/80 [[data-theme=black]_&]:from-transparent [[data-theme=black]_&]:via-transparent [[data-theme=black]_&]:to-[#F6E4B6]/30"></div>
        <Navbar />
        <main className="container relative z-20 mx-auto w-full max-w-[1440px]">{children}</main>
      </body>
    </html>
  );
}
